### ISSUE TITLE
NR crashes: Error: WebSocket is not open: readyState 0 (CONNECTING)

### ISSUE THREAD

**Issue by andreypopov** [NRCHKB/node-red-contrib-unifi-os#76]
It happens several times every day.

7 Aug 07:46:04 - [red] Uncaught Exception:
7 Aug 07:46:04 - [error] Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.ping (/home/server/.node-red/node_modules/node-red-contrib-unifi-os/node_modules/ws/lib/websocket.js:354:13)
    at SharedProtectWebSocket.<anonymous> (/home/server/.node-red/node_modules/node-red-contrib-unifi-os/build/SharedProtectWebSocket.js:74:72)
    at Generator.next (<anonymous>)
    at fulfilled (/home/server/.node-red/node_modules/node-red-contrib-unifi-os/build/SharedProtectWebSocket.js:5:58)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 2h 18min 52.597s CPU time.
nodered.service: Scheduled restart job, restart counter is at 3.
Stopped Node-RED graphical event wiring tool.
nodered.service: Consumed 2h 18min 52.597s CPU time.
Started Node-RED graphical event wiring tool.

**Comment by Supergiovane** [comment]
Hi andreypopov,
Please take a look here
https://github.com/NRCHKB/node-red-contrib-unifi-os/issues/72#issuecomment-2273272317

**Comment by marcus-j-davies** [comment]
This is fixed with Beta 3 (recently published)  - courtesy of @Supergiovane
