### ISSUE TITLE
_j.split is not a function

### ISSUE THREAD

**Issue by linkworx-stijnvandenbroucke** [NRCHKB/node-red-contrib-unifi-os#84]
Hi, I have a fatal error aftere update

23 Sep 08:33:06 - [red] Uncaught Exception:
23 Sep 08:33:06 - [error] TypeError: _j.split is not a function
    at init.<anonymous> (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/build/nodes/Protect.js:233:105)
    at Generator.next (<anonymous>)
    at /home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/build/nodes/Protect.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/build/nodes/Protect.js:27:12)
    at Object.handleUpdate (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/build/nodes/Protect.js:139:40)
    at /home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/build/SharedProtectWebSocket.js:175:22
    at Array.forEach (<anonymous>)
    at SharedProtectWebSocket.processData (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/build/SharedProtectWebSocket.js:173:37)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:517:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/node_modules/ws/lib/receiver.js:569:14)
    at Receiver.getData (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/node_modules/ws/lib/receiver.js:496:10)
    at Receiver.startLoop (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/node_modules/ws/lib/receiver.js:167:16)
    at Receiver._write (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/node_modules/ws/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Receiver.Writable.write (node:internal/streams/writable:337:10)
    at TLSSocket.socketOnData (/home/grafana/.node-red/node_modules/node-red-contrib-unifi-os/node_modules/ws/lib/websocket.js:1355:35)

**Comment by linkworx-stijnvandenbroucke** [comment]
@crxporter Something I can assist to solve this?

**Comment by crxporter** [comment]
What is your nodered version and node version?

**Comment by linkworx-stijnvandenbroucke** [comment]
Hi,

Nodered version: 4.0.3
Node version: 1.1.0

I did some additional testing.
Screenshot 1: I was using one protect node per camera and select the different event per camera.
Screenshot 2: I've changed this to 1 protect node for all camera's and handle the events in some logic after the protect node. In this last setup, the error is not there (with the same set of camera's).

Screenshot 1:
[cid:7896eaaa-d999-4c39-9d21-fc8a39327ee4]

Screenshot 2:

[cid:220f2055-61d3-453c-a981-60a67d0976f5]

________________________________

**Comment by crxporter** [comment]
I was looking for nodejs version, too. 
Screenshots did not come through. 

Interesting that it works as expected with just one node. Let's get @marcus-j-davies attention if he's got a moment to look
